### ISSUE TITLE
First glance: bad command names and syntax

### ISSUE THREAD

**Issue by iredmail** [mig1984/bashible#3]
Dear @mig1984,

I found bashible on Hacker News, just want to share some thoughts about bashible based on my own Ansible experience.

I checked documents under `docs/` directory and some examples, i think the biggest issue of bashible might be unclear command names and syntax, they could/should be greatly improved.

About command names, for example:

- `may_fail`: better be `ignore_errors` (used by Ansible)
- `add_line`, `append_line`, `prepend_line`: maybe merge to one command named `lineinfile` (line in file. used by Ansible), and just use some argument to indicate it should be appended or prepended if not present.
- `fill_var`: why it's called `fill` and not something like `set`?
- `var_empty`: maybe rename to 'is_empty_var'? easier to understand.
- ...

About syntax, i'd like to compare bashible with [cdist](https://www.cdi.st/). Although cdist itself is wrote in Python-3, but cdist user just writes bash scripting in cdist syntax.

Compare bashible's `add_line`, `append_line` and `prepend_line` for example, compare them with cdist's `__line` command (it's called `cdist type` instead of command (bashible) or task (ansible), but let's call it command below and save me some typing). Please allow me to copy cdist official examples below:

```
# Manage a hosts entry for www.example.com.
__line /etc/hosts \
    --line '127.0.0.2 www.example.com'

# Manage another hosts entry for test.example.com.
__line hosts:test.example.com \
    --file /etc/hosts \
    --line '127.0.0.3 test.example.com'

# Remove the line starting with TIMEZONE from the /etc/rc.conf file.
__line legacy_timezone \
   --file /etc/rc.conf \
   --regex 'TIMEZONE=.*' \
   --state absent

# Insert a line before another one.
__line password-auth-local:classify \
    --file /etc/pam.d/password-auth-local \
    --line '-session required pam_exec.so debug log=/tmp/classify.log /usr/local/libexec/classify' \
    --before '^session[[:space:]]+include[[:space:]]+password-auth-ac$'

# Insert a line after another one.
__line password-auth-local:classify \
    --file /etc/pam.d/password-auth-local \
    --line '-session required pam_exec.so debug log=/tmp/classify.log /usr/local/libexec/classify' \
    --after '^session[[:space:]]+include[[:space:]]+password-auth-ac$'
```

One command may support multiple arguments to generate different results. This syntax (IMO) is so much better than bashible.

Just my 2 cents. hope it helps a little. :)

**Comment by mig1984** [comment]
Hi!

finally I have some time to work on bashible. Thank you for your suggestions, I think you are right, it's important to be as much "compatible" with existing tools like Ansible.

> - `may_fail`: better be `ignore_errors` (used by Ansible)

Ok, it could also be an alias. But I would prefer the ignore_errors only, because it's always better when there is just one way.

> - `add_line`, `append_line`, `prepend_line`: maybe merge to one command named `lineinfile` (line in file. used by Ansible), and just use some argument to indicate it should be appended or prepended if not present.

I will have a look at the lineinfile and __line. My concern was to make it not too complicated, one function per an action. If there are optional arguments, then you have to parse them, etc.

But indeed, the difference between add_line and append_line is not obvious.

Maybe it won't be so complicated to rewrite these basic Ansible modules in Bash. It's just about time. 

In the beginning I thought bashible is just wasting of time, but now i see there are almost 500 stars (thanks the Hacker News). Perhaps it is interresting to other people, too.

> - `fill_var`: why it's called `fill` and not something like `set`?

Originally it was called set_var. Then i found out, there is no way to set a variable like foo=bar. In the end, there are two functions: set_var and fill_var. These commands do the same,

- set_var foo bar
- fill_var foo echo bar

Indeed, it's not very clear. Maybe it could work like this:

- foo = bar
- result foo echo bar

The "-" function would test the presence of the "=" as the second argument and set the variable.
The result function would store both exitcode and stdout. The exitcode is already stored as a newly created function foo(). 
It would additionaly store the output as a variable $foo.

I would get rid of the set_var and fill_var then.

> - `var_empty`: maybe rename to 'is_empty_var'? easier to understand.

OK, sounds better.

Thanks for ideas!
Jan
